---
title: "nofafsa_dialing_gr_5050_21TW3"
output: html_document
---

```{r load-libraries, include=FALSE}
# setup
library(DBI)
library(odbc)
library(tidyverse)
library(gt)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  fig.width = 10,
  fig.height = 6
)
```



#database connection
```{r connection-string,include=FALSE}
#database connection
con_data_reporting <- dbConnect(odbc::odbc(), .connection_string = "Driver={SQL Server Native Client 11.0};\n                          Server=COCE-DS-LSTNR,50222;\n                          Database=Data_Reporting;\n                          trusted_connection=yes;")
```


#import data from query -don't use this, I am working on a new query that pulls from the experiment table
```{r}
fye_df <- dbGetQuery(
  conn = con_data_reporting, 
  statement = read_file(
    file = here::here("sql","fye_tasks.sql")
  )
) %>% as_tibble()
```


#database connection 50333
```{r connection-string,include=FALSE}
#database connection
con_data_reporting <- dbConnect(odbc::odbc(), .connection_string = "Driver={SQL Server Native Client 11.0};\n                          Server=COCE-LSTNR,50333;\n                          Database=AARDA;\n                          trusted_connection=yes;")
```




#import data from query
```{r}
melt_df <- dbGetQuery(
  conn = con_data_reporting, 
  statement = read_file(
    file = here::here("sql","melt.sql")
  )
) %>% as_tibble()
```




# joining melt to results -->
```{r}
fye_results_melt_df <-
as_tibble() %>%
  inner_join(x = fye_df,
          y = melt_df,
          by = c("colleague_id" = "StudentColleagueID")) 
#%>%
  #filter(StudentColleagueID != "Unknown") 

#results_calls %>% replace_na()

```



```{r}
fye_results_melt_df %>% 
  filter(EnrolledDay1 == 1 & EnrolledDay15 ==0)
```


#Aggregate test results to date
```{r}
fye_results <- 
  fye_results_melt_df %>% 
  filter(!is.na(test_group)) %>% 
  group_by(testing_group) %>% 
  summarise(
      InPopulation = n(), 
       Logins = sum(`FYE-101 Login`),
       `Login Rate` = sum(`FYE-101 Login`)/n(),
        #`Regs` = sum(registration_count),
      #`Reg Rate` = sum(registration_count) / n(),
      `Post Start Melts` = sum(EnrolledDay1)-sum(EnrolledDay15),
      `Post Start Melt Rate` = 1-sum(EnrolledDay15)/sum(EnrolledDay1),
       `Day 1 Starts` = sum(EnrolledDay1),
      `Day 1 Start Rate` = sum(EnrolledDay1)/n(),
      `Day 15 Starts` = sum(EnrolledDay15),
      `Day 15 Start Rate` = sum(EnrolledDay15)/n()
       #Starts = sum(start_count),
      #`Start Rate` = sum(start_count) / n()
      #`FAFSA to Enroll Rate` = sum(Regs) / sum(fafsa_completed),
       #`App to Enroll` = sum(Regs) /sum(Apps) 
  ) %>% 
  rename(`Test Group` = testing_group) %>% 
 gt() %>%
     fmt_percent(columns = vars(
      `Day 1 Start Rate`,
      `Day 15 Start Rate`,
      `Post Start Melt Rate`,
      `Login Rate`,
      `Day 15 Start Rate`
     ), decimals = 1) %>%
     fmt_number(columns = vars(
    InPopulation,
    Logins,
    `Post Start Melts`,
    `Day 1 Starts`,
    `Day 15 Starts`
     ), decimals = 0) %>%
      data_color(columns = vars(`Logins`), colors = "lightblue") %>%
   tab_header(
    title = md("21EW4 FYE-101 Task & Email: Test vs. Control")) %>% 
    tab_footnote(
    footnote = "Definition of post-start melt",
    locations = cells_column_labels(
      columns = vars(`Post Start Melts`))) %>%
    tab_source_note(
    source_note = c("Data Source:  Unify Opportunity, Course Enrollment - retrieved on 3/18/21"))
  #%>%
     #data_color(columns = vars(`Melt Rate`), colors = "lightgreen") %>%
    #tab_options(
      # column_labels.font.size = 13,
      # table.font.size = 12
    #)

#Starts = registered, had course interaction, stage name in unify = Started
#Day 15 Starts = for day 15 when opportunity is moved to "closed won"

#would be interesting to see broken out based on day 15 start vs. whether they logged in or not, irrespective of which test group they were in

##need to be extra careful with filters to make sure I am grabbing the right test population

# let's put these in this order:  move post start melts & post start melt rate to right

fye_results
  
```



```{r}
# Overall results save
fye_results %>% gtsave(filename = "fye_task_21EW4_20210317.png", path = here::here("imgs"))
```